application: wallyklinko
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: app.main.application

libraries:
- name: django
  version: latest
